import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/context/AuthContext";

const lora = Lora({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Readify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <div className="wrapper">
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
